(defpackage janitor/stockmarket/util
  (:use :cl)
  (:export
    #:ticker-oid-ht))

(in-package :janitor/stockmarket/util)

(defvar ticker-oid-ht
  (let ((ht (make-hash-table :test 'equal)))
    (setf (gethash "NHY" ht) 1)
    (setf (gethash "EQNR" ht) 2)
    (setf (gethash "YAR" ht) 3)
    (setf (gethash "SDRL" ht) 4)
    (setf (gethash "ACY" ht) 5)
    (setf (gethash "TEL" ht) 6)
    (setf (gethash "OBX" ht) 7)
    (setf (gethash "MHG" ht) 8)
    (setf (gethash "ORK" ht) 9)
    (setf (gethash "DNBNOR" ht) 10)
    (setf (gethash "REC" ht) 11)
    (setf (gethash "PGS" ht) 12)
    (setf (gethash "RCL" ht) 13)
    (setf (gethash "STB" ht) 14)
    (setf (gethash "TAA" ht) 15)
    (setf (gethash "TGS" ht) 16)
    (setf (gethash "TOM" ht) 17)
    (setf (gethash "AKSO" ht) 18)
    (setf (gethash "DNB" ht) 19)
    (setf (gethash "DNO" ht) 20)
    (setf (gethash "GJF" ht) 21)
    (setf (gethash "NSG" ht) 22)
    (setf (gethash "SUBC" ht) 23)
    (setf (gethash "OSEBX" ht) 24)
    (setf (gethash "AKERBP" ht) 25)
    (setf (gethash "BWLPG" ht) 26)
    (setf (gethash "BAKKA" ht) 27)
    (setf (gethash "GOGL" ht) 28)
    (setf (gethash "NAS" ht) 29)
    ht))
