--- new migration 2026-07-08 ---

create schema stockmarket_dev;

create table stockmarket_dev.optionpurchase (
    oid integer generated by default as identity primary key,
    opid integer not null,
    dx date default now(),
    price stockmarket.price not null,
    volume stockmarket.volume not null,
    status stockmarket.status default 0,
    transaction_cost stockmarket.price default 0 not null,
    purchase_type integer default 0 not null,
    spot stockmarket.price default 0 not null,
    buy stockmarket.price not null
);

alter table only stockmarket.optionpurchase
    add constraint optionpurchase_dev_opid_fkey foreign key (opid) references stockmarket.optionx(oid);

create table stockmarket_dev.optionsale (
    oid integer generated by default as identity primary key,
    purchase_id integer not null,
    dx date default now(),
    price stockmarket.price not null,
    volume stockmarket.volume not null,
    status stockmarket.status default 0,
    transaction_cost stockmarket.price default 0 not null
);

alter table only stockmarket_dev.optionsale
    add constraint optionsale_dev_purchase_id_fkey foreign key (purchase_id) references stockmarket_dev.optionpurchase(oid);

alter table only stockmarket_dev.optionsale
    add constraint optionsale_dev_status_id_fkey foreign key (status) references stockmarket.status_codes(oid);

create table stockmarket_dev.critter (
    oid integer generated by default as identity primary key,
    status stockmarket.status default 0,
    critter_type stockmarket.critter_type,
    sell_vol stockmarket.sell_volume default 10,
    purchase_id integer,
    sale_id integer
);

alter table only stockmarket_dev.critter
    add constraint critter_dev_purchase_id_fkey foreign key (purchase_id) references stockmarket_dev.optionpurchase(oid);

alter table only stockmarket_dev.critter
    add constraint critter_dev_sale_id_fkey foreign key (sale_id) references stockmarket_dev.optionsale(oid);

alter table only stockmarket_dev.critter
    add constraint critter_dev_status_id_fkey foreign key (status) references stockmarket.status_codes(oid);

create table stockmarket_dev.accept_rules (
    oid integer generated by default as identity primary key,
    value stockmarket.price not null,
    rtyp integer not null,
    active stockmarket.bool_type default 'y'::bpchar,
    description stockmarket.rule_desc,
    cid integer
);

alter table only stockmarket_dev.accept_rules
    add constraint acc_dev_critter_fkey foreign key (cid) references stockmarket_dev.critter(oid);

alter table only stockmarket.accept_rules
    add constraint acc_dev_rules_type_fkey foreign key (rtyp) references stockmarket.rule_types(oid) on delete restrict;

insert into stockmarket.migrations (version,comment) values (1783503813,'Stockmarket dev');


/*
select 
    'alter table ' || table_schema || '."' || table_name || '" alter ' || column_name || ' drop default; ' ||
    'drop sequence ' || substring(column_default, 9, length(column_default)-19) || ' cascade; ' ||
    'alter table ' || table_schema || '."' || table_name || '" alter column ' || column_name || ' add generated always as identity; ' ||
    'select setval(pg_get_serial_sequence(''' || table_schema || '.' || table_name || ''', ''' || column_name || '''), 
    coalesce((select max(' || column_name || ') from ' || table_schema || '.' || table_name || '), 0) + 1, false);'
from information_schema.columns
where column_default like 'nextval%';
*/
